Xmoor.Main/Areas/Manager/Controllers/RoleApplicationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
using Xmoor.DataAccess;
using Xmoor.Main.Areas.Manager.ViewModels;
using Xmoor.Models;
using Xmoor.Utility;

namespace Xmoor.Main.Areas.Manager.Controllers
{
    [Area("Manager")]
    public class RoleApplicationsController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public RoleApplicationsController(ApplicationDbContext db, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            _db = db;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles =StaticDetails.Role_Manager)]
        public IActionResult NewApplication()
        {
            NewRoleVM roleVMObj = new NewRoleVM();
            roleVMObj.RoleList = _db.Roles.Select(
                    i => new SelectListItem
                    {
                        Text = i.RoleName,
                        Value = i.RoleId.ToString()
                    }
                ).ToList();
            roleVMObj.DepartmentList = _db.Department.Select(
                    i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    }
                ).ToList();
            roleVMObj.RoleOpenning = new RoleOpennings();
            return View(roleVMObj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = StaticDetails.Role_Manager)]
        public IActionResult NewApplication(NewRoleVM roleVMObj)
        {
            if (_signInManager.IsSignedIn(User))
            {
                roleVMObj.RoleOpenning.EditorId = (int)_db.RegistrationLog.FirstOrDefault(o => o.ApplicationUserId == (string)_userManager.GetUserId(User)).StaffDetailsId;
                roleVMObj.RoleOpenning.Published = true;
                if (!ModelState.IsValid)
                {
                    roleVMObj.RoleList = _db.Roles.Select(
                   i => new SelectListItem
                   {
                       Text = i.RoleName,
                       Value = i.RoleId.ToString()
                   }
               ).ToList();
                    roleVMObj.DepartmentList = _db.Department.Select(
                            i => new SelectListItem
                            {
                                Text = i.Name,
                                Value = i.Id.ToString()
                            }
                        ).ToList();
                    roleVMObj.RoleOpenning = new RoleOpennings();
                    return View(roleVMObj);
                }
                _db.RoleOpennings.Add(roleVMObj.RoleOpenning);
                _db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = StaticDetails.Role_Manager)]
        public IActionResult SaveDraft(NewRoleVM roleVMObj)
        {
            if (_signInManager.IsSignedIn(User))
            {
                roleVMObj.RoleOpenning.Published = true;
                if (!ModelState.IsValid)
                {
                    return View("CreateNew", roleVMObj);
                }
                _db.RoleOpennings.Add(roleVMObj.RoleOpenning);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

    }

}

Xmoor.Main/Areas/Manager/Views/RoleApplications/Index.cshtml
@{
    ViewData["Title"] = "ApplicationDashboard";
}

@section CSS{
    <style>
        .mainContainer{
            justify-content:center;
        }

        .dashHeader {
            width:90%;
            max-width:1000px;
            box-shadow: 0 0 5px 1px;
            border-radius:5px;
        }
    </style>
}



<div class="mainContainer">
    <div class="dashHeader"> 
        <a asp-area="Manager" asp-controller="RoleApplications" asp-action="NewApplication">New Application</a>
    </div>
</div>

Xmoor.Main/Areas/Manager/Views/RoleApplications/NewApplication.cshtml
@using Xmoor.Main.Areas.Manager.ViewModels;
@model NewRoleVM

@section CSS{
    <style>
        .mainContainer {
            text-align: centre;
            width: 100%;
            margin-bottom: 20px !important;
        }

        #registerForm {
            display: grid;
            width: 100%;
            grid-template-columns: 40% 40%;
            max-width: 1000px;
            justify-content: center;
            margin-left: auto;
            margin-right: auto;
            column-gap: 30px !important;
            row-gap: 20px;
        }

        #buttonContainer {
            width: 100%;
            display: flex;
            grid-column: 1/span 2;
            align-items: center;
            justify-content: space-between;
        }

        .span2 {
            grid-column: 1/span 2;
        }

    </style>
}


<div class="mainContainer">

    <form id="registerForm" method="post" asp-action="NewApplication">
        <h1 class="span2">Create New Job Application</h1>

        <label asp-for="RoleOpenning.Title"></label>
        <input asp-for="RoleOpenning.Title" />

        <label asp-for="RoleOpenning.RoleId"></label>
        <select asp-for="RoleOpenning.RoleId" asp-items="@Model.RoleList">
            <option selected disabled>PLEASE SELECT</option>
        </select>

        <label asp-for="RoleOpenning.DepartmentId"></label>
        <select asp-for="RoleOpenning.DepartmentId" asp-items="@Model.DepartmentList">
            <option selected disabled>PLEASE SELECT</option>
        </select>

        <label class="span2" asp-for="RoleOpenning.Description"></label>
        <textarea class="span2" asp-for=RoleOpenning.Description rows="30" style="width:100%;resize:none;padding:10px;"></textarea>

        

        <label asp-for="RoleOpenning.Salary"></label>
        <input asp-for="RoleOpenning.Salary" />

        <label asp-for="RoleOpenning.WorkingHours"></label>
        <input asp-for="RoleOpenning.WorkingHours" />

        <label asp-for="RoleOpenning.OpeningDate"></label>
        <input asp-for="RoleOpenning.OpeningDate" type="date" id="txtDate" />

        <label asp-for="RoleOpenning.CloseDate"></label>
        <input asp-for="RoleOpenning.CloseDate" type="date" id="txtDate" />

        <label asp-for="RoleOpenning.KeyWords"></label>
        <input asp-for="RoleOpenning.KeyWords" />

        <div id="#buttonContainer">
            <button type="submit">PUBLISH</button>
        </div>

    </form>

</div>

@section Scripts{
    <script>

        $(function () {
            var dtToday = new Date();

            var month = dtToday.getMonth() + 1;
            var day = dtToday.getDate();
            var year = dtToday.getFullYear();
            if (month < 10)
                month = '0' + month.toString();
            if (day < 10)
                day = '0' + day.toString();

            var maxDate = year + '-' + month + '-' + day;

            // or instead:
            // var maxDate = dtToday.toISOString().substr(0, 10);

            $('#txtDate').attr('min', maxDate);
        });
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
}