Xmoor.Main/Areas/Applicant/Controllers/ApplicationsController.cs
using Microsoft.AspNetCore.Mvc;
using Xmoor.DataAccess;
using Xmoor.Main.Areas.Applicant.ViewModels;
using Xmoor.Models;

namespace Xmoor.Main.Areas.Applicant.Controllers
{
    [Area("Applicant")]
    public class ApplicationsController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ApplicationsController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<RoleOpennings> roleOpenigs =  _db.RoleOpennings.ToList();
            return View(roleOpenigs);
        }

        [HttpPost]
        public IActionResult  Index(string search)
        {
            IEnumerable<RoleOpennings> roleOpenigs = _db.RoleOpennings.Where(o=>o.Title.Contains(search) || o.KeyWords.Contains(search));
            return View(roleOpenigs);
        }


        [HttpGet]
        public IActionResult ViewApplication(int Id)
        {
            ViewApplicationVM applicationVM = new ViewApplicationVM();
            var roleOpenning = (from roleOpenings in _db.RoleOpennings
                               join departments in _db.Department on roleOpenings.DepartmentId equals departments.Id
                               join role in _db.Roles on roleOpenings.RoleId equals role.RoleId
                               select new
                               {
                                   TIT=roleOpenings.Title,
                                   CD=roleOpenings.CloseDate,
                                   DES=roleOpenings.Description,
                                   WH=roleOpenings.WorkingHours,
                                   RN=role.RoleName,
                                   DN=departments.Name
                               }).FirstOrDefault();

            applicationVM.Id = Id;
            applicationVM.Title = roleOpenning.TIT;
            applicationVM.RoleName = roleOpenning.RN;
            applicationVM.Description = roleOpenning.DES;
            applicationVM.DepartmentName = roleOpenning.DN;
            applicationVM.WorkingHours = roleOpenning.WH;
            applicationVM.CloseDate = roleOpenning.CD;
            return View(applicationVM);
        }

    }
}

Xmoor.Main/Areas/Applicant/Controllers/SearchController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Xmoor.DataAccess;

namespace Xmoor.Main.Areas.Applicant.Controllers
{
    
    [Route("api/[controller]")]
    [ApiController]
    public class SearchController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public SearchController(ApplicationDbContext db)
        {
            _db = db;
        }

        [Produces("application/json")]
        [HttpGet("search")]
        public async Task<IActionResult> Search()
        {
            try
            {
                string searchString = HttpContext.Request.Query["searchString"].ToString();
                var searchResult =  _db.RoleOpennings.Where(o=>o.Description.Contains(searchString)).ToList();
                return Ok(searchResult);
            }
            catch
            {
                return BadRequest();
            }
        }
    }
}

Xmoor.Main/Areas/Applicant/Views/Applications/Index.cshtml
@model IEnumerable<RoleOpennings>


@section CSS {
    <style>
        .searchBarContainer {
            justify-content: right;
            width: 90%;
            max-width: 1000px;
            margin-left: auto !important;
            margin-right: auto !important;
            box-shadow: 0 0 5px 2px;
            padding: 10px;
            margin: 20px;
            min-height: 100vh;
            border-radius: 5px;
        }

        .search {
            width: 100%;
            display: grid;
            grid-template-columns: 1fr 230px;
        }

            .search input {
                padding: 10px;
                font-size: 1rem;
            }

        .searchButton {
            background-color: rgb(35, 35, 71);
            color: white;
            border-radius: 5px;
        }

        .searchResultsContainer {
            display: grid;
            row-gap: 10px;
            margin-top: 20px;
        }

        .resultItem {
            display: grid;
            width: 90%;
            margin-left: auto;
            margin-right: auto;
            grid-template-columns: 1fr 200px;
            border: 2px solid rgb(65, 65, 78);
            padding: 10px 20px;
            border-radius: 5px;
            margin-bottom: 20px;
            padding-bottom:30px;
        }

            .resultItem a {
                text-decoration: none;
                color: white;
                background-color: rgb(53, 53, 65);
                padding: 5px 10px;
                border-radius: 5px;
            }

        .viewButtonContainer {
            display: flex;
            align-items: center;
            justify-content: right;
            padding-right: 40px;
        }

        .roleDescription {
            display: grid;
        }

            .roleDescription ul {
                margin: 10px;
                margin-bottom: 0 !important;
                max-width: 80%;
            }

            .roleDescription li {
                display: inline-block !important;
                margin: 0;
                margin-right: 10px;
            }

    </style>

}


<div class="searchBarContainer">
    <br>
    <form method="post" class="search" asp-action="Index" style="width: 100%;">
        <input id="searchString" name="search" type="text" class="searchString">
        <input type="submit" class="searchButton" value="Search" style="margin-left: 10px;">
    </form>
    <br>
    <hr>

    <!--Search Results Container-->
    <div class="searchResultsContainer">

        @{
            foreach(var i in Model)
            {
                <div class="resultItem">
                    <div class="roleDescription">
                        <h3>@i.Title</h3>
                        <ul>
                            <li><b>Salary: </b> @i.Salary</li>
                            <li><b>Hours: </b>@i.WorkingHours</li>
                        </ul>
                    </div>
                    <div class="viewButtonContainer"><a asp-area="Applicant" asp-controller="Applications" asp-action="ViewApplication" asp-route-id="@i.Id">View Job</a></div>
                </div>
            }
        }
    </div>

</div>

@section Scripts{
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js" integrity="sha256-xLD7nhI62fcsEZK2/v8LsBcb4lG7dgULkuXoXB/j91c=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>

    <script>
        $(document).ready(function(){
            $("#searchString").autocomplete({
                source: 'api/Search/Search'
            })
        });
    </script>
}

Xmoor.Main/Areas/Applicant/Views/Applications/Search.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Xmoor.Main/Areas/Applicant/Views/Applications/ViewApplication.cshtml
@using Xmoor.Main.Areas.Applicant.ViewModels;
@model ViewApplicationVM

@section CSS {
    <style>
        .appplication {
            margin-left: auto;
            margin-right: auto;
            width: 90%;
            max-width: 1000px;
            margin-top: 20px;
            box-shadow: 0 0 5px 1px;
            border-radius: 5px;
            padding: 20px;
            box-sizing: border-box;
            min-height: 80vh;
            margin-bottom:20px;
        }

        .applicationHeading {
            display: flex;
            align-items: center;
            justify-content: space-between;
        }

            .applicationHeading a {
                text-decoration: none;
                color: white;
                background-color: rgb(51, 51, 77);
                padding: 5px 10px;
                border-radius: 5px;
            }


        .keyInfo {
            display: flex;
            justify-content: left;
            margin-bottom: 10px;
            padding:10px;
        }

        .keyInfo div {
            display:flex;
            margin-right: 10px;
            color: white;
            background-color: gray;
            border-radius: 5px;
        }

        .bluePart{
            background: rgb(51, 51, 77) !important;
            padding:0 10px;
        }

    </style>

}


<div class="mainContainer">
    <div class="appplication">
        <h5 style="margin-bottom:0;">Job Post</h5>
        <div class="applicationHeading">
            <h1>@Model.Title</h1>
            <a href="http://">Apply Now</a>
        </div>
        <hr/>
        <div class="keyInfo">
            <div> 
                
                <div class="bluePart">Department</div>
                <div>@Model.DepartmentName</div>
            </div>
            <div>
                <div class="bluePart">Role</div>
                <div>@Model.RoleName</div>
            </div>
            <div>
                <div class="bluePart">Working Hours</div>
                <div>@Model.WorkingHours</div>
            </div>
            <div>
                <div class="bluePart">Application Close</div>
                <div>@Model.CloseDate</div>
            </div>
        </div>
        <hr>
        <h4>Description</h4>
        <div class="description">
            @Model.Description
        </div>

    </div>
</div>